### ISSUE TITLE
{Bug} Play games profile and Photos sync not working

### ISSUE THREAD

**Issue by ghost** [IRedDragonICY/Disable-Unwanted-Google-Play-Services#1]
Title says it all

**Comment by IRedDragonICY** [comment]
Can u provide some screenshot or logcat. I'm checking g play games or g photos syncing properly. I'm not disable some services like sync.

**Comment by ghost** [comment]
G play games profile is not loading and can't log in any games. It should revert all the applicated changes if I remove or disable this module. I'm not seeing that either. Thanks 

![image](https://user-images.githubusercontent.com/89753463/186915567-29c92e69-8c71-4255-a2c4-8ad5bdbf3ec4.png)

**Comment by IRedDragonICY** [comment]
You can try enable service below in terminal. Next Update, if you want to use my module, just delete line from header #google play games. I haven't made a disable selector yet. Thank you too for trying my magisk module. 

Command:
pm enable (service)

List Service google play games:
com.google.android.gms/com.google.android.gms.gp.gameservice.GameService com.google.android.gms/com.google.android.gms.games.chimera.GamesUploadServiceProxy com.google.android.gms/com.google.android.gms.games.chimera.GamesSyncServiceNotificationProxy com.google.android.gms/com.google.android.gms.games.chimera.GamesSyncServiceMainProxy com.google.android.gms/com.google.android.gms.games.chimera.GamesSignInServiceProxy com.google.android.gms/com.google.android.gms.games.chimera.GamesSignInIntentServiceProxy com.google.android.gms/com.google.android.gms.games.chimera.GamesAsyncServiceProxy com.google.android.gms/com.google.android.gms.games.chimera.GamesAndroidServiceProxy
