### ISSUE TITLE
"Find my device" can't find the device location 

### ISSUE THREAD

**Issue by aanneion** [IRedDragonICY/Disable-Unwanted-Google-Play-Services#3]
Please allow the "find my device" service. It's very necessary sometimes in the emergency.

**Comment by IRedDragonICY** [comment]
what device are you? write the description of the device name, android version and google play service version.  No problem if you didn't press turn off button find my device
![Screenshot_2022-09-30-13-06-29-054_com chrome dev](https://user-images.githubusercontent.com/98265563/193201901-18da943b-290e-4576-9b0a-3a62d84ebe27.jpg)

**Comment by aanneion** [comment]
Redmi note 11, crdroid 8.9, android 12.1
Google play services version 22.33.16 (190400-474895102)

Find my device option is ON, Location is also ON. But both find my device and google maps location is not working.

**Comment by IRedDragonICY** [comment]
1. uninstall module and run uninstall.sh
2. modify module from service.sh. U can use any text editor and zarchiver for replace file
-    delete all line from #Location
-    replace service.sh
3. flash modification module again

**Comment by aanneion** [comment]
Thanks. Trying and letting you know

**Comment by aanneion** [comment]
Fixed now. Thanks.
