### ISSUE TITLE
Please create an easy executable unninstall.sh

### ISSUE THREAD

**Issue by WUIX69** [IRedDragonICY/Disable-Unwanted-Google-Play-Services#4]
Good Day Sir

Can you atleaset make an easy executable unninstall.sh for us, so it can be more easy to rollback if we screwed up disabling some important service of google..

idk if i done it right, i copy all the codes in unninstall.sh and paste it directly on termux then run it, i saw some "java.execution.error" in their don't know if its fine or not tho..

Thanks for understanding

**Comment by IRedDragonICY** [comment]
To enable all GMS services, you may try turn on all services from [MyAndroidTools](https://www.myandroidtools.com/) for easiest way. Sorry,i'm currently do not have enought time to optimize uninstall.sh.

**Comment by WUIX69** [comment]
> To enable all GMS services, you may try turn on all services from [MyAndroidTools](https://www.myandroidtools.com/) for easiest way. Sorry,i'm currently do not have enought time to optimize uninstall.sh.

I think im good now, i literally copied everything from unninstall.sh then paste it directly in termux.. i know that it seems odd to copy a bunch of codes and paste it on a single line.. but i think its fine now

In case if you've wondered why am asking for a quick unninstall.sh, cause recently after i installed this module, the logs from magisk is showing some kind of this

E: and W: instead of I: from executing and (0 != 4) idk what its all about tho, so i decided to unninstall it and re-install it again now its fine the weird logs is gone now.. Can you care to explain what happen ?

**Comment by IRedDragonICY** [comment]
Sorry, I don't know bro. I'm think it related problem from Magisk 26.x++
